import Link from "next/link";

export const metadata = {
  title: "Docs",
  description: "How Liquidify works: autonomous fee collection, buybacks, and liquidity pool management.",
};

const sections = [
  {
    label: "Overview",
    title: "What is Liquidify?",
    content: [
      "$Liquidify is a Solana token with an autonomous agent that manages all creator fees. There is no team wallet. There is no manual process. Every single fee generated by trading goes back into strengthening the token.",
      "The agent runs continuously, monitoring market conditions and executing when the time is right. All actions are logged and verifiable on-chain.",
    ],
  },
  {
    label: "Pre-migration",
    title: "Phase 1: Buybacks",
    content: [
      "Before the token migrates from the bonding curve to an AMM, the agent uses 100% of collected fees to buy $Liquidify off the market.",
      "The agent checks if the token is still on the bonding curve. If it is, it fetches the bonding curve state (reserves, supply), calculates how many tokens it can get for the accumulated SOL, and executes the buy through the Pump.fun bonding curve program.",
      "If the token has already migrated to PumpSwap AMM, the buyback goes through the AMM instead. The agent finds the canonical pool, fetches swap state, and executes a buy with 2% slippage tolerance.",
      "After every buyback, the agent checks its token balance and burns everything. All tokens in the agent wallet get destroyed using the Token-2022 burn instruction. This reduces supply permanently.",
    ],
  },
  {
    label: "Post-migration",
    title: "Phase 2: Liquidity",
    content: [
      "Once $Liquidify migrates to PumpSwap AMM, the strategy shifts entirely. Instead of buybacks, 100% of fees go into deepening the liquidity pool.",
      "Adding LP happens in two transactions. First, 65% of the SOL is used to buy tokens through the AMM. This gives the agent the tokens it needs for the deposit. Then, the remaining 35% SOL plus the bought tokens are deposited together as liquidity.",
      "The deposit uses PumpSwap's SDK to automatically calculate the right ratio of tokens to SOL and how many LP tokens the agent receives. Slippage is set to 10% for deposits since LP operations are more sensitive to price movement.",
      "The cycle compounds: more trading generates more fees, which deepen the pool, which enables more trading with less slippage.",
    ],
  },
  {
    label: "The agent",
    title: "How the agent works",
    content: [
      "The agent is a script running on a local machine. Each cycle it checks the creator fee vault on-chain. If enough SOL has accumulated, it claims the fees and decides what to do.",
      "Pre-migration: claim fees, buyback tokens, burn everything. Post-migration: claim fees, add liquidity to the pool. The decision is automatic based on whether the token has migrated to AMM or not.",
      "After each action, the agent logs the result to a Supabase database. The website reads from this database every few seconds to display live stats and the thinking feed.",
    ],
  },
  {
    label: "Thinking feed",
    title: "The thinking station",
    content: [
      "After every cycle, the agent generates a short summary of what it did and why. This is created using OpenAI and stored in Supabase alongside the cycle data.",
      "The website displays these thoughts in real time with a blinking cursor, giving the appearance of an AI that's actively thinking. Each thought shows the action type (buyback, monitoring, idle) and when it happened.",
      "If no OpenAI key is configured, the agent falls back to plain text summaries of the cycle results.",
    ],
  },
  {
    label: "Data flow",
    title: "Architecture",
    content: [
      "Solana blockchain: the agent interacts with on-chain programs to claim fees, execute swaps via bonding curve or AMM, burn tokens, and add liquidity.",
      "Supabase: stores cumulative stats (total collected, total added to pool), the activity feed, and the latest agent thought. Updated after every cycle.",
      "Vercel: the website fetches data from Supabase and displays it. Only the anon key is exposed to the frontend. The website is read-only.",
    ],
  },
  {
    label: "Platform",
    title: "Coming soon: launch your own",
    content: [
      "The same engine that powers $Liquidify will be available as a platform. Launch your own token with a built-in autonomous LP agent.",
      "Same fee collection. Same buyback-to-LP pipeline. Same real-time thinking feed. Just your token.",
    ],
  },
];

export default function DocsPage() {
  return (
    <main className="min-h-screen px-6 lg:px-10 pt-28 pb-20">
      <div className="max-w-[800px] mx-auto">
        <Link href="/" className="text-[13px] text-white/20 hover:text-white/50 transition-colors mb-12 inline-block">
          &#8592; Back
        </Link>

        <h1 className="text-[clamp(2rem,5vw,3.5rem)] font-bold tracking-[-0.04em] leading-[1.1] text-white/90 mb-4">
          Documentation
        </h1>
        <p className="text-[16px] text-white/30 leading-[1.7] mb-16">
          How $Liquidify works, from fee collection to autonomous liquidity management.
        </p>

        <div className="space-y-16">
          {sections.map((s) => (
            <section key={s.label} className="scroll-mt-24">
              <p className="text-[11px] text-white/15 uppercase tracking-[0.2em] font-mono mb-3">{s.label}</p>
              <h2 className="text-[22px] font-bold tracking-[-0.02em] text-white/80 mb-5">{s.title}</h2>
              <div className="space-y-4">
                {s.content.map((p, i) => (
                  <p key={i} className="text-[15px] leading-[1.8] text-white/30">{p}</p>
                ))}
              </div>
              
            </section>
          ))}
        </div>

        <div className="mt-20 text-center">
          <Link href="/" className="text-[14px] accent hover:text-white transition-colors">
            &#8592; Back to Liquidify
          </Link>
        </div>
      </div>
    </main>
  );
}
